server:
  port: 9000

spring:
  application:
    name: authorization-server
  security:
    oauth2:
      authorizationserver:
        issuer-url: http://127.0.0.1:9000

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nb_users
    username: postgres
#    password: postgres
    password: 1111
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
        show_sql: true