server:
  port: 9000

spring:
  application:
    name: authorization-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nb_users
    username: postgres
    password: 1111
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
        show_sql: true