server:
  port: 9000

application:
  kafka:
    topic: "auth-mail-topic"

spring:
  application:
    name: authorization-server
  security:
    oauth2:
      authorizationserver:
        issuer-url: http://127.0.0.1:9000

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nb_users
    username: postgres
#    password: postgres
    password: 1111
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  kafka:
    producer:
      #    key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092
      client-id: auth-mail-producer
  #    properties:
  #      spring:
  #        json:
  #          add:
  #            type:
  #              headers: false